name : Jobs para atualizar dados
    run-on : ubuntu-latest
    passos :
      # cartões de resumo
      - usa : actions/checkout@v2
      - usa : vn7n24fzkq/github-profile-summary-cards@release
        ambiente :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        com :
          USERNAME : ${{ github.repository_owner }}

      # Animação de cobra
      - usa : Platane/snk@master
        id : cobra-gif
        com :
          github_user_name : Bruno19458177
          svg_out_path : dist/github-contribution-grid-snake.svg
      - usa : crazy-max/ghaction-github-pages@v2.1.3
        com :
          target_branch : saída
          build_dir : dist
        ambiente :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
